apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victorialogs-backup-pvc
  namespace: logging 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path